<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="2.0"
	xmlns:xsl="http://www.w3.org/1999/XSL/Transform" 
	xmlns:eg="http://www.tei-c.org/ns/Examples"
	xmlns:tei="http://www.tei-c.org/ns/1.0" 
	xmlns:xd="http://www.oxygenxml.com/ns/doc/xsl" 
	xmlns:exsl="http://exslt.org/common"
	xmlns:msxsl="urn:schemas-microsoft-com:xslt"
	xmlns:fn="http://www.w3.org/2005/xpath-functions"
	xmlns:xhtml="http://www.w3.org/1999/xhtml"
	extension-element-prefixes="exsl msxsl"
	xmlns="http://www.w3.org/1999/xhtml" 
	xpath-default-namespace="http://www.w3.org/1999/xhtml"
	exclude-result-prefixes="xsl tei xd eg fn #default">
  
  <xsl:import href="teibp.xsl"/>
  
  <xd:doc scope="stylesheet">
		<xd:desc>
			<xd:p><xd:b>Author:</xd:b> Ashley M. Clark</xd:p>
			<xd:p>This stylesheet takes the full HTML page generated by teibp.xsl and 
			  returns only the content of the HTML body, wrapped in a div.</xd:p>
		</xd:desc>
	</xd:doc>
  
  <xsl:template match="/">
    <xsl:variable name="fullDoc" as="node()">
      <xsl:apply-imports/>
    </xsl:variable>
    <div class="teibp">
      <xsl:copy-of select="$fullDoc/body/*"/>
    </div>
  </xsl:template>
  
</xsl:stylesheet>